version: '2'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_roomba
    ports: 
      - 5001:5001
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5001
    environment: 
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
    volumes:
      ['./:/app']
